const S={records:[],data:{},view:'roadmap',selected:null,filters:{q:'',time:'all',stage:'all',actor:'all',year:'all',major:false}};
const $=q=>document.querySelector(q), $$=q=>Array.from(document.querySelectorAll(q));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lab=v=>String(v??'').replace(/[_-]/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const year=r=>String(r.date||r.target_date||'').slice(0,4), dkey=r=>r.date||r.target_date||'', tclass=r=>r.record_type==='prospective'?'prospective':(r.temporal_status||'observed');
const actors=r=>r.record_type==='prospective'?(r.actors||[]):[r.institution];
const ANCHORS=new Set(['2022-12-fda-modernization-2','2024-09-24-fda-istand-liver-chip','2025-04-10-fda-roadmap','2025-04-29-nih-human-based-initiative','2025-12-aim-mash-qualification','2026-08-27-epa-regulatory-use','2026-08-31-fda-icmra-endotoxin','prospective-mps-reusable-qualification','prospective-international-convergence','prospective-multi-context-displacement','prospective-composable-qualification']);
async function json(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);return r.json()}
function link(url,text='Source ↗'){return url?`<a href="${esc(url)}" target="_blank" rel="noopener">${esc(text)}</a>`:''}
function fill(sel,vals){const el=$(sel);if(!el)return;vals.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=lab(v);el.appendChild(o)})}
function filtered(){const f=S.filters,q=f.q.toLowerCase();return S.records.filter(r=>{if(f.major&&!r.major_milestone)return false;if(f.time!=='all'&&tclass(r)!==f.time)return false;if(f.stage!=='all'&&!(r.stage||[]).includes(f.stage))return false;if(f.actor!=='all'&&!actors(r).includes(f.actor))return false;if(f.year!=='all'&&year(r)!==f.year)return false;const b=[r.title,r.summary,r.why_it_matters,r.rationale,r.institution,...actors(r),...(r.stage||[]),...(r.domain||[])].join(' ').toLowerCase();return !q||b.includes(q)})}
function dotClass(r){if(r.record_type==='prospective')return'prospective-dot';if((r.stage||[]).includes('adoption'))return'adoption-dot';if((r.stage||[]).includes('qualification'))return'qualification-dot';return'commitment-dot'}
function tooltip(r){return `<span class="snake-tooltip"><span class="snake-tooltip-date">${esc(r.display_date||year(r))} · ${esc(r.institution||'Prospective')}</span><b>${esc(r.title)}</b><span>${esc(r.summary)}</span><em>${esc((r.stage||[]).map(lab).join(' · '))}</em></span>`}
function renderSnake(rows){const box=$('#snake-timeline');if(!box)return;if(!rows.length){box.innerHTML='<p class="empty">No roadmap records match the current filters.</p>';return}const a=rows.slice().sort((x,y)=>dkey(x).localeCompare(dkey(y))), parts=Array.from({length:5},()=>[]);a.forEach((r,i)=>parts[Math.min(4,Math.floor(i*5/a.length))].push(r));let h='';for(let ri=4;ri>=0;ri--){const dir=ri%2===0?'ltr':'rtl', raw=parts[ri], show=dir==='rtl'?raw.slice().reverse():raw;h+=`<div class="snake-row ${dir}"><div class="snake-row-years"><span>${esc(year(show[0]||{}))}</span><span>${esc(year(show[show.length-1]||{}))}</span></div><div class="snake-track">${show.map(r=>`<div class="snake-node ${ANCHORS.has(r.id)?'anchor':''}"><button class="snake-dot ${dotClass(r)} ${S.selected===r.id?'selected':''}" data-id="${esc(r.id)}" aria-label="${esc(r.title)}">${tooltip(r)}</button>${ANCHORS.has(r.id)?`<span class="snake-anchor-text"><b>${esc(year(r))}</b>${esc(r.title)}</span>`:''}</div>`).join('')}</div></div>`;if(ri>0)h+=`<div class="snake-turn ${(ri-1)%2===0?'right':'left'}"><span></span></div>`}box.innerHTML=h;$$('.snake-dot').forEach(b=>b.onclick=()=>{S.selected=b.dataset.id;renderRoadmap();renderSelected(S.records.find(r=>r.id===S.selected))})}
function renderSelected(r){const box=$('#selected-detail');if(!box)return;if(!r){box.innerHTML='<div class="selected-placeholder">Select a roadmap dot to expand the record here.</div>';return}const pro=r.record_type==='prospective';box.innerHTML=`<article class="selected-card ${pro?'prospective-selected':''}"><div class="selected-meta"><span>${esc(r.display_date||year(r))}</span><span>${esc(r.institution||'Prospective')}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p>${pro?`<p><b>Why it matters.</b> ${esc(r.rationale)}</p>`:r.why_it_matters?`<p><b>Why it matters.</b> ${esc(r.why_it_matters)}</p>`:''}<div class="tags">${(r.stage||[]).map(x=>`<span class="tag">${esc(lab(x))}</span>`).join('')}</div><p class="source">${pro?'Actors: '+esc((r.actors||[]).join(' · ')):link(r.source_url,'Primary source ↗')}</p></article>`}
function fullCard(r){return r.record_type==='prospective'?`<article class="event prospective"><div class="event-date">${esc(r.display_date)}</div><div class="event-card"><div class="institution">Prospective</div><h2>${esc(r.title)}</h2><p>${esc(r.summary)}</p><p class="why"><b>Why it matters.</b> ${esc(r.rationale)}</p></div></article>`:`<article class="event"><div class="event-date">${esc(r.display_date)}</div><div class="event-card"><div class="institution">${esc(r.institution)}</div><h2>${esc(r.title)}</h2><p>${esc(r.summary)}</p>${r.why_it_matters?`<p class="why"><b>Why it matters.</b> ${esc(r.why_it_matters)}</p>`:''}<p class="source">${link(r.source_url,'Primary source ↗')}</p></div></article>`}
function renderRoadmap(){const rs=filtered();[['#visible-count',rs.length],['#commitment-count',rs.filter(r=>(r.stage||[]).includes('commitment')).length],['#qualification-count',rs.filter(r=>(r.stage||[]).includes('qualification')).length],['#adoption-count',rs.filter(r=>(r.stage||[]).includes('adoption')).length],['#prospective-count',rs.filter(r=>r.record_type==='prospective').length]].forEach(([q,v])=>{if($(q))$(q).textContent=v});renderSnake(rs);const tl=$('#timeline');if(tl)tl.innerHTML=rs.slice().sort((a,b)=>dkey(b).localeCompare(dkey(a))).map(fullCard).join('');if(S.selected)renderSelected(S.records.find(r=>r.id===S.selected))}
function evidenceCard(c){const url=c.fda_review_source||c.ema_assessment_source||c.health_canada_source||c.pmda_assessment_source||c.regulator_authored_synthesis;return `<article class="data-card"><div class="institution">${esc(c.regulator)}</div><h4>${esc(c.product)}</h4><p><b>Regulatory impact.</b> ${esc(c.regulatory_impact)}</p><p><b>Legacy evidence.</b> ${esc(c.legacy_evidence_displaced_or_unavailable)}</p><div class="tags"><span class="tag">${c.counts_as_animal_displacement?'Animal displacement':'NAM reliance'}</span></div><p class="source">${link(url,'Regulator source ↗')}</p></article>`}
function contextCard(c){return `<article class="data-card"><div class="institution">${esc(c.regulator)}</div><h4>${esc(c.decision_context)}</h4><p><b>Legacy component.</b> ${esc(c.legacy_animal_component)}</p><p><b>Alternative.</b> ${esc(c.alternative)}</p><p class="source">${link(c.source_url)}</p></article>`}
function metricCard(m){let n=m.studies_saved?`${m.studies_saved.toLocaleString()} studies`:m.waivers_granted?`${m.waivers_granted.toLocaleString()} waivers`:m.value!=null?`${Number(m.value).toLocaleString()} ${String(m.unit||'').replace(/_/g,' ')}`:lab(m.metric_type);return `<article class="metric-card"><div class="institution">${esc(m.regulator)}</div><strong>${esc(n)}</strong><h4>${esc(m.context)}</h4><p>${esc(m.basis)}</p><p class="source">${link(m.source_url)}</p></article>`}
async function loadEvidence(){if(S.data.named)return;try{const [named,contexts,metrics]=await Promise.all([json('data/named_regulatory_adoption.json'),json('data/regulatory_contexts.json'),json('data/displacement_metrics.json')]);Object.assign(S.data,{named,contexts,metrics});renderEvidence()}catch(e){showError('evidence',e)}}
function renderEvidence(){const n=S.data.named?.cases||[],c=S.data.contexts?.contexts||[],m=S.data.metrics?.metrics||[];[['#named-count',n.length],['#strict-displacement-count',n.filter(x=>x.counts_as_animal_displacement).length],['#context-count',c.length],['#realized-metric-count',m.filter(x=>String(x.realized_or_estimated||'').startsWith('realized')).length]].forEach(([q,v])=>{if($(q))$(q).textContent=v});if($('#metric-grid'))$('#metric-grid').innerHTML=m.map(metricCard).join('');const strict=$('#strict-only')?.checked;if($('#named-case-grid'))$('#named-case-grid').innerHTML=n.filter(x=>!strict||x.counts_as_animal_displacement).map(evidenceCard).join('');const major=$('#major-contexts-only')?.checked;if($('#context-grid'))$('#context-grid').innerHTML=c.filter(x=>!major||x.major_context).map(contextCard).join('')}
function comparatorCard(c){return `<article class="data-card"><div class="institution">${esc(c.regulator)} · ${esc(c.modality)}</div><h4>${esc(c.product)}</h4><p><b>Species/model relevance.</b> ${esc(c.species_relevance_basis)}</p><p><b>General/repeat-dose toxicology.</b> ${esc(lab(c.general_repeat_toxicology))}</p><p><b>Animal studies retained.</b> ${esc(c.animal_studies_retained)}</p><p class="source">${link(c.source_url,'Regulator source ↗')}</p></article>`}
async function loadAnalysis(){if(S.data.comparators)return;try{const [comparators,surrogates]=await Promise.all([json('data/species_relevance_comparators.json'),json('data/surrogate_toxicology_cases.json')]);Object.assign(S.data,{comparators,surrogates});renderAnalysis()}catch(e){showError('analysis',e)}}
function renderAnalysis(){const c=S.data.comparators?.comparators||[],s=S.data.surrogates?.cases||[];[['#comparator-count',c.length],['#nonrelevant-count',c.filter(x=>x.relevant_species_status!=='relevant').length],['#relevant-count',c.filter(x=>x.relevant_species_status==='relevant').length],['#surrogate-count',s.length]].forEach(([q,v])=>{if($(q))$(q).textContent=v});if($('#comparator-grid'))$('#comparator-grid').innerHTML=c.map(comparatorCard).join('');if($('#surrogate-grid'))$('#surrogate-grid').innerHTML=s.map(x=>`<article class="data-card"><div class="institution">${esc(x.regulator)} · ${esc(x.approval_year)}</div><h4>${esc(x.product)}</h4><p>${esc(x.surrogate_strategy)}</p><p class="source">${link(x.source_url,'Regulator source ↗')}</p></article>`).join('');const p=S.data.surrogates?.policy_contrast;if(p&&$('#policy-contrast'))$('#policy-contrast').innerHTML=`<div class="institution">Policy contrast · ${esc(p.regulator)}</div><h4>Current approaches are not fully converged</h4><p>${esc(p.policy)}</p><p>${esc(p.interpretation)}</p><p class="source">${link(p.source_url,'MHRA source ↗')}</p>`}
function showError(view,e){const p=$(`#view-${view}`);if(p){const d=document.createElement('div');d.className='caution';d.innerHTML=`<b>This view could not load.</b> ${esc(e.message)}`;p.prepend(d)}}
async function setView(v){v=['roadmap','evidence','analysis','methods'].includes(v)?v:'roadmap';S.view=v;$$('.view-panel').forEach(p=>p.hidden=p.id!==`view-${v}`);$$('.view-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(location.hash!==`#${v}`)history.replaceState(null,'',`#${v}`);if(v==='roadmap')renderRoadmap();if(v==='evidence')await loadEvidence();if(v==='analysis')await loadAnalysis()}
function bind(){const on=(q,ev,fn)=>{$(q)?.addEventListener(ev,fn)};on('#search','input',e=>{S.filters.q=e.target.value;renderRoadmap()});on('#temporal','change',e=>{S.filters.time=e.target.value;renderRoadmap()});on('#stage','change',e=>{S.filters.stage=e.target.value;renderRoadmap()});on('#institution','change',e=>{S.filters.actor=e.target.value;renderRoadmap()});on('#year','change',e=>{S.filters.year=e.target.value;renderRoadmap()});on('#major','change',e=>{S.filters.major=e.target.checked;renderRoadmap()});on('#reset','click',()=>{S.filters={q:'',time:'all',stage:'all',actor:'all',year:'all',major:false};$('#search').value='';$('#temporal').value=$('#stage').value=$('#institution').value=$('#year').value='all';$('#major').checked=false;renderRoadmap()});on('#toggle-chronology','click',e=>{const w=$('#full-chronology-wrap');w.hidden=!w.hidden;e.currentTarget.textContent=w.hidden?'Open full vertical chronology':'Collapse full vertical chronology';e.currentTarget.setAttribute('aria-expanded',String(!w.hidden))});on('#strict-only','change',renderEvidence);on('#major-contexts-only','change',renderEvidence);$$('.view-tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));window.addEventListener('hashchange',()=>setView(location.hash.slice(1)))}
async function init(){try{const [events,prospective]=await Promise.all([json('data/events.json'),json('data/prospective.json')]);S.records=[...(events.events||[]).map(x=>({...x,record_type:'event'})),...(prospective.milestones||[]).map(x=>({...x,record_type:'prospective'}))];$('#last-updated').textContent=`Updated ${[events.updated,prospective.updated].filter(Boolean).sort().reverse()[0]||'—'}`;$('#event-count').textContent=`${events.events.length} observed/emerging · ${prospective.milestones.length} prospective`;fill('#stage',Array.from(new Set(S.records.flatMap(r=>r.stage||[]))).sort());fill('#institution',Array.from(new Set(S.records.flatMap(actors).filter(Boolean))).sort());fill('#year',Array.from(new Set(S.records.map(year).filter(Boolean))).sort().reverse());bind();renderSelected(null);await setView(location.hash.slice(1)||'roadmap')}catch(e){console.error(e);$('#event-count').textContent='Roadmap load error';$('#snake-timeline').innerHTML=`<div class="caution"><b>Roadmap data could not be loaded.</b> ${esc(e.message)}</div>`}}
init();