const state={records:[],search:'',stage:'all',institution:'all',year:'all',temporal:'all',major:false,view:'roadmap',selectedId:null,chronologyOpen:false,data:{}};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const label=s=>String(s??'').replaceAll('_',' ').replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase());
const boolLabel=v=>v===true?'Yes':v===false?'No':label(v);
const ANCHOR_IDS=new Set([
  '2022-12-fda-modernization-2',
  '2024-09-24-fda-istand-liver-chip',
  '2025-04-10-fda-roadmap',
  '2025-04-29-nih-human-based-initiative',
  '2025-12-aim-mash-qualification',
  '2026-03-18-fda-general-nam-guidance',
  '2026-06-nih-oriva',
  '2026-08-27-epa-regulatory-use',
  '2026-08-31-fda-icmra-endotoxin',
  'prospective-mps-reusable-qualification',
  'prospective-international-convergence',
  'prospective-multi-context-displacement',
  'prospective-composable-qualification'
]);

function fillSelect(el,values){for(const value of values){const o=document.createElement('option');o.value=value;o.textContent=label(value);el.appendChild(o)}}
function normalizedYear(r){return String(r.date||r.target_date||r.approval_or_decision_year||r.approval_year||'').slice(0,4)}
function temporalClass(r){return r.record_type==='prospective'?'prospective':(r.temporal_status||'observed')}
function actorsFor(r){return r.record_type==='prospective'?(r.actors||[]):[r.institution]}
function countStage(records,stage){return records.filter(r=>(r.stage||[]).includes(stage)).length}
function sourceLink(url,text='Primary source ↗'){return url?`<a href="${esc(url)}" target="_blank" rel="noopener">${esc(text)}</a>`:''}
function dateKey(r){return r.date||r.target_date||''}
function shortDate(r){return r.display_date||dateKey(r).slice(0,4)}
function institutionLabel(r){return r.record_type==='prospective'?'Prospective':(r.institution||'')}

function filteredRoadmap(){const q=state.search.toLowerCase().trim();return state.records.filter(r=>{
  if(state.major&&!r.major_milestone)return false;
  if(state.temporal!=='all'&&temporalClass(r)!==state.temporal)return false;
  if(state.stage!=='all'&&!(r.stage||[]).includes(state.stage))return false;
  if(state.institution!=='all'&&!actorsFor(r).includes(state.institution))return false;
  if(state.year!=='all'&&normalizedYear(r)!==state.year)return false;
  const blob=`${r.title} ${r.summary} ${r.why_it_matters||''} ${r.rationale||''} ${r.institution||''} ${(r.actors||[]).join(' ')} ${(r.stage||[]).join(' ')} ${(r.domain||[]).join(' ')}`.toLowerCase();
  return !q||blob.includes(q);
})}

function renderObserved(e){return `<article class="event"><div class="event-date">${esc(e.display_date)}</div><div class="event-card"><div class="event-top"><div><div class="institution">${esc(e.institution)}</div><h2>${esc(e.title)}</h2></div><div class="badges"><span class="status time">${esc(label(temporalClass(e)))}</span><span class="status ${e.source_status==='primary_source_verified'?'verified':''}">${esc(label(e.source_status))}</span></div></div><p>${esc(e.summary)}</p>${e.why_it_matters?`<p class="why"><b>Why it matters.</b> ${esc(e.why_it_matters)}</p>`:''}<div class="tags">${(e.stage||[]).map(x=>`<span class="tag">${esc(label(x))}</span>`).join('')}${(e.domain||[]).map(x=>`<span class="tag">${esc(label(x))}</span>`).join('')}${e.major_milestone?'<span class="tag major-tag">Major milestone</span>':''}</div><p class="source">${e.source_url?`${sourceLink(e.source_url)} · `:''}${esc(e.manuscript_ref||'')}</p></div></article>`}
function renderProspective(m){const criteria=(m.success_criteria||[]).map(x=>`<li>${esc(x)}</li>`).join('');return `<article class="event prospective"><div class="event-date">${esc(m.display_date)}</div><div class="event-card"><div class="event-top"><div><div class="institution">Prospective · ${esc(label(m.type))}</div><h2>${esc(m.title)}</h2></div><div class="badges"><span class="status prospective-status">Prospective</span><span class="status">${esc(label(m.status))}</span></div></div><p>${esc(m.summary)}</p><p class="why"><b>Why it matters.</b> ${esc(m.rationale)}</p>${criteria?`<div class="criteria"><b>What would count as success</b><ul>${criteria}</ul></div>`:''}<div class="tags">${(m.stage||[]).map(x=>`<span class="tag">${esc(label(x))}</span>`).join('')}${(m.domain||[]).map(x=>`<span class="tag">${esc(label(x))}</span>`).join('')}${m.major_milestone?'<span class="tag major-tag">Major milestone</span>':''}</div><p class="source">Actors: ${esc((m.actors||[]).join(' · '))}${m.paper_origin?` · Origin: ${esc(m.paper_origin)}`:''}</p></div></article>`}

function renderSelectedRecord(r){if(!r){$('#selected-detail').innerHTML='<div class="selected-placeholder">Select a roadmap dot to expand the record here.</div>';return}const prospective=r.record_type==='prospective';const criteria=prospective?(r.success_criteria||[]).map(x=>`<li>${esc(x)}</li>`).join(''):'';$('#selected-detail').innerHTML=`<article class="selected-card ${prospective?'prospective-selected':''}"><div class="selected-meta"><span>${esc(shortDate(r))}</span><span>${esc(institutionLabel(r))}</span><span>${esc(label(temporalClass(r)))}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p>${prospective?`<p><b>Why it matters.</b> ${esc(r.rationale||'')}</p>${criteria?`<div class="criteria"><b>What would count as success</b><ul>${criteria}</ul></div>`:''}`:(r.why_it_matters?`<p><b>Why it matters.</b> ${esc(r.why_it_matters)}</p>`:'')}<div class="tags">${(r.stage||[]).map(x=>`<span class="tag">${esc(label(x))}</span>`).join('')}${(r.domain||[]).map(x=>`<span class="tag">${esc(label(x))}</span>`).join('')}</div><p class="source">${prospective?`Actors: ${esc((r.actors||[]).join(' · '))}`:sourceLink(r.source_url,'Primary source ↗')}</p></article>`}
}

function snakeClass(r){const stages=r.stage||[];if(r.record_type==='prospective')return 'prospective-dot';if(stages.includes('adoption'))return 'adoption-dot';if(stages.includes('qualification'))return 'qualification-dot';return 'commitment-dot'}
function anchorLabel(r){const y=normalizedYear(r);const t=r.title.replace(/^FDA\s+/i,'').replace(/^NIH\s+/i,'');return `<span class="snake-anchor-text"><b>${esc(y)}</b>${esc(t)}</span>`}
function snakeTooltip(r){const stage=(r.stage||[]).map(label).join(' · ');return `<span class="snake-tooltip"><span class="snake-tooltip-date">${esc(shortDate(r))} · ${esc(institutionLabel(r))}</span><b>${esc(r.title)}</b><span>${esc(r.summary)}</span><em>${esc(stage)}</em></span>`}

function renderSnake(records){const target=$('#snake-timeline');if(!records.length){target.innerHTML='<p class="empty">No roadmap records match the current filters.</p>';return}const chronological=records.slice().sort((a,b)=>dateKey(a).localeCompare(dateKey(b)));const rowCount=5;const rows=Array.from({length:rowCount},()=>[]);chronological.forEach((r,i)=>rows[Math.min(rowCount-1,Math.floor(i*rowCount/chronological.length))].push(r));const html=[];for(let visual=rowCount-1;visual>=0;visual--){const chronologicalRow=visual;const direction=chronologicalRow%2===0?'ltr':'rtl';const rowRecords=rows[chronologicalRow].slice();const display=direction==='rtl'?rowRecords.slice().reverse():rowRecords;const startYear=rowRecords.length?normalizedYear(rowRecords[0]):'';const endYear=rowRecords.length?normalizedYear(rowRecords[rowRecords.length-1]):'';html.push(`<div class="snake-row ${direction}" data-row="${chronologicalRow}"><div class="snake-row-years"><span>${esc(direction==='ltr'?startYear:endYear)}</span><span>${esc(direction==='ltr'?endYear:startYear)}</span></div><div class="snake-track">${display.map(r=>{const selected=state.selectedId===r.id?' selected':'';const anchor=ANCHOR_IDS.has(r.id)&&!state.major;return `<div class="snake-node${anchor?' anchor':''}"><button class="snake-dot ${snakeClass(r)}${selected}" type="button" data-record-id="${esc(r.id)}" aria-label="${esc(`${shortDate(r)}: ${r.title}`)}">${snakeTooltip(r)}</button>${anchor?anchorLabel(r):''}</div>`}).join('')}</div></div>`);if(visual>0){const lowerChronological=visual-1;const side=lowerChronological%2===0?'right':'left';html.push(`<div class="snake-turn ${side}"><span></span></div>`)}}
target.innerHTML=html.join('');$$('.snake-dot').forEach(dot=>dot.addEventListener('click',()=>{state.selectedId=dot.dataset.recordId;const rec=state.records.find(r=>r.id===state.selectedId);renderSelectedRecord(rec);renderSnake(filteredRoadmap());$('#selected-detail').scrollIntoView({behavior:'smooth',block:'nearest'})}))}

function renderRoadmap(){const records=filteredRoadmap();$('#visible-count').textContent=records.length;$('#commitment-count').textContent=countStage(records,'commitment');$('#qualification-count').textContent=countStage(records,'qualification');$('#adoption-count').textContent=countStage(records,'adoption');$('#prospective-count').textContent=records.filter(r=>r.record_type==='prospective').length;renderSnake(records);const sorted=records.slice().sort((a,b)=>dateKey(b).localeCompare(dateKey(a)));$('#empty').hidden=sorted.length>0;$('#timeline').innerHTML=sorted.map(r=>r.record_type==='prospective'?renderProspective(r):renderObserved(r)).join('');if(state.selectedId){const selected=records.find(r=>r.id===state.selectedId)||state.records.find(r=>r.id===state.selectedId);renderSelectedRecord(selected)}}

function metricValue(m){if(m.studies_saved)return `${Number(m.studies_saved).toLocaleString()} studies`;if(m.waivers_granted)return `${Number(m.waivers_granted).toLocaleString()} waivers`;if(m.animal_reduction_min!=null&&m.animal_reduction_max!=null)return `${Number(m.animal_reduction_min).toLocaleString()}–${Number(m.animal_reduction_max).toLocaleString()} animals`;if(m.value!=null){const unit=String(m.unit||'').replaceAll('_',' ');return `${Number(m.value).toLocaleString()} ${unit}`}return label(m.metric_type)}
function metricSecondary(m){const bits=[];if(m.animal_reduction_min!=null&&m.animal_reduction_max!=null&&m.studies_saved)bits.push(`${Number(m.animal_reduction_min).toLocaleString()}–${Number(m.animal_reduction_max).toLocaleString()} animals`);if(m.cost_savings_usd)bits.push(`$${Number(m.cost_savings_usd).toLocaleString()} estimated sponsor savings`);return bits.join(' · ')}
function renderMetric(m){return `<article class="metric-card"><div class="institution">${esc(m.regulator)}</div><strong>${esc(metricValue(m))}</strong><h4>${esc(m.context)}</h4>${metricSecondary(m)?`<p>${esc(metricSecondary(m))}</p>`:''}<p>${esc(m.basis)}</p><div class="tags"><span class="tag">${esc(label(m.realized_or_estimated))}</span><span class="tag">${m.human_based_replacement===true?'Human-based':m.human_based_replacement==='mixed'?'Mixed evidence':'Broader NAM / waiver'}</span></div><p class="source">${sourceLink(m.source_url)}</p></article>`}

function adoptionClass(c){if(c.counts_as_animal_displacement)return 'Animal displacement';if(c.counts_as_named_nam_adoption)return 'NAM regulatory reliance';return 'Other evidence substitution'}
function firstSource(c){for(const k of ['fda_review_source','ema_assessment_source','health_canada_source','pmda_assessment_source','regulator_authored_synthesis','ema_supporting_source'])if(c[k])return c[k];return null}
function renderNamedCase(c){return `<article class="data-card"><div class="card-head"><div><div class="institution">${esc(c.regulator)}</div><h4>${esc(c.product)}</h4></div><span class="status ${c.counts_as_animal_displacement?'verified':''}">${esc(adoptionClass(c))}</span></div><p><b>Alternative evidence.</b> ${esc(c.nam)}</p><p><b>Regulatory impact.</b> ${esc(c.regulatory_impact)}</p><p><b>Legacy evidence.</b> ${esc(c.legacy_evidence_displaced_or_unavailable)}</p><div class="tags"><span class="tag">${esc(c.jurisdiction)}</span><span class="tag">${esc(c.approval_or_decision_year)}</span><span class="tag">${esc(label(c.evidence_strength))}</span></div>${c.note?`<p class="micro-note">${esc(c.note)}</p>`:''}<p class="source">${sourceLink(firstSource(c),'Regulator source ↗')}</p></article>`}
function renderContext(c){return `<article class="data-card"><div class="card-head"><div><div class="institution">${esc(c.regulator)}</div><h4>${esc(c.decision_context)}</h4></div><span class="status ${c.regulatory_status==='implemented_regulatory_use'?'verified':''}">${esc(label(c.regulatory_status))}</span></div><p><b>Legacy component.</b> ${esc(c.legacy_animal_component)}</p><p><b>Alternative.</b> ${esc(c.alternative)}</p><div class="tags"><span class="tag">${esc(label(c.displacement_type))}</span><span class="tag">Human-based: ${esc(boolLabel(c.human_based))}</span>${c.major_context?'<span class="tag major-tag">Major context</span>':''}</div><p class="micro-note">${esc(c.source_note)}</p><p class="source">${sourceLink(c.source_url)}</p></article>`}
function renderEvidence(){const named=state.data.named.cases||[];const contexts=state.data.contexts.contexts||[];const metrics=state.data.metrics.metrics||[];$('#named-count').textContent=named.length;$('#strict-displacement-count').textContent=named.filter(c=>c.counts_as_animal_displacement).length;$('#context-count').textContent=contexts.length;$('#realized-metric-count').textContent=metrics.filter(m=>String(m.realized_or_estimated||'').startsWith('realized')).length;$('#metric-grid').innerHTML=metrics.map(renderMetric).join('');const strict=$('#strict-only').checked;$('#named-case-grid').innerHTML=named.filter(c=>!strict||c.counts_as_animal_displacement).sort((a,b)=>(b.approval_or_decision_year||0)-(a.approval_or_decision_year||0)).map(renderNamedCase).join('');const major=$('#major-contexts-only').checked;$('#context-grid').innerHTML=contexts.filter(c=>!major||c.major_context).map(renderContext).join('')}

function relevanceBucket(c){return String(c.relevant_species_status||'').startsWith('relevant')?'relevant':'nonrelevant'}
function outcomeTone(c){const o=String(c.general_repeat_toxicology||'');return o.includes('retained')&&!o.includes('omitted')?'retained':o.includes('omitted')?'omitted':'tailored'}
function renderComparator(c){const bucket=relevanceBucket(c);return `<article class="data-card comparator-card ${bucket}"><div class="card-head"><div><div class="institution">${esc(c.regulator)} · ${esc(c.modality)}</div><h4>${esc(c.product)}</h4></div><span class="status ${bucket==='relevant'?'':'verified'}">${esc(label(c.relevant_species_status))}</span></div><p><b>Species/model relevance.</b> ${esc(c.species_relevance_basis)}</p><p><b>General / repeat-dose toxicology.</b> ${esc(label(c.general_repeat_toxicology))}</p><p><b>Animal studies retained.</b> ${esc(c.animal_studies_retained)}</p>${(c.human_relevant_evidence||[]).length?`<p><b>Human-relevant evidence.</b> ${esc(c.human_relevant_evidence.join('; '))}</p>`:''}<div class="tags"><span class="tag">${esc(c.target)}</span><span class="tag">${esc(label(c.comparator_class))}</span><span class="tag">Outcome: ${esc(label(outcomeTone(c)))}</span></div><p class="source">${sourceLink(c.source_url,'Regulator source ↗')}</p></article>`}
function renderSurrogate(c){return `<article class="data-card"><div class="institution">${esc(c.regulator)} · ${esc(c.approval_year)}</div><h4>${esc(c.product)}</h4><p><b>Why the clinical product was not directly testable.</b> ${esc(c.clinical_product_species_relevance)}</p><p><b>Surrogate strategy.</b> ${esc(c.surrogate_strategy)}</p><p class="micro-note">${esc(c.why_it_matters)}</p><p class="source">${sourceLink(c.source_url,'Regulator source ↗')}</p></article>`}
function renderAnalysis(){const comps=state.data.comparators.comparators||[];const sur=state.data.surrogates.cases||[];$('#comparator-count').textContent=comps.length;$('#nonrelevant-count').textContent=comps.filter(c=>relevanceBucket(c)==='nonrelevant').length;$('#relevant-count').textContent=comps.filter(c=>relevanceBucket(c)==='relevant').length;$('#surrogate-count').textContent=sur.length;$('#comparator-grid').innerHTML=comps.slice().sort((a,b)=>relevanceBucket(a).localeCompare(relevanceBucket(b))||a.product.localeCompare(b.product)).map(renderComparator).join('');$('#surrogate-grid').innerHTML=sur.map(renderSurrogate).join('');const pc=state.data.surrogates.policy_contrast||{};$('#policy-contrast').innerHTML=`<div class="institution">Policy contrast · ${esc(pc.regulator)} · ${esc(pc.date)}</div><h4>Current regulatory approaches are not fully converged</h4><p>${esc(pc.policy)}</p><p>${esc(pc.interpretation)}</p><p class="source">${sourceLink(pc.source_url,'MHRA source ↗')}</p>`}

function setView(view){const allowed=['roadmap','evidence','analysis','methods'];state.view=allowed.includes(view)?view:'roadmap';$$('.view-panel').forEach(p=>p.hidden=p.id!==`view-${state.view}`);$$('.view-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));if(location.hash!==`#${state.view}`)history.replaceState(null,'',`#${state.view}`);if(state.view==='roadmap')renderRoadmap();if(state.view==='evidence')renderEvidence();if(state.view==='analysis')renderAnalysis();window.scrollTo({top:0,behavior:'instant'})}
function toggleChronology(){state.chronologyOpen=!state.chronologyOpen;$('#full-chronology-wrap').hidden=!state.chronologyOpen;$('#toggle-chronology').setAttribute('aria-expanded',String(state.chronologyOpen));$('#toggle-chronology').textContent=state.chronologyOpen?'Collapse full vertical chronology':'Open full vertical chronology'}
function bind(){$('#search').addEventListener('input',e=>{state.search=e.target.value;renderRoadmap()});$('#temporal').addEventListener('change',e=>{state.temporal=e.target.value;renderRoadmap()});$('#stage').addEventListener('change',e=>{state.stage=e.target.value;renderRoadmap()});$('#institution').addEventListener('change',e=>{state.institution=e.target.value;renderRoadmap()});$('#year').addEventListener('change',e=>{state.year=e.target.value;renderRoadmap()});$('#major').addEventListener('change',e=>{state.major=e.target.checked;renderRoadmap()});$('#reset').addEventListener('click',()=>{state.search='';state.stage='all';state.institution='all';state.year='all';state.temporal='all';state.major=false;$('#search').value='';$('#stage').value='all';$('#institution').value='all';$('#year').value='all';$('#temporal').value='all';$('#major').checked=false;renderRoadmap()});$('#toggle-chronology').addEventListener('click',toggleChronology);$('#strict-only').addEventListener('change',renderEvidence);$('#major-contexts-only').addEventListener('change',renderEvidence);$$('.view-tab').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));window.addEventListener('hashchange',()=>setView(location.hash.slice(1)))}
async function loadJSON(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path} HTTP ${r.status}`);return r.json()}
async function init(){try{const [events,prospective,named,contexts,metrics,comparators,surrogates]=await Promise.all([loadJSON('data/events.json'),loadJSON('data/prospective.json'),loadJSON('data/named_regulatory_adoption.json'),loadJSON('data/regulatory_contexts.json'),loadJSON('data/displacement_metrics.json'),loadJSON('data/species_relevance_comparators.json'),loadJSON('data/surrogate_toxicology_cases.json')]);state.data={events,prospective,named,contexts,metrics,comparators,surrogates};state.records=[...events.events.map(e=>({...e,record_type:'event'})),...prospective.milestones.map(m=>({...m,record_type:'prospective'}))];const updated=[events.updated,prospective.updated,named.updated,contexts.updated,metrics.updated,comparators.updated,surrogates.updated].filter(Boolean).sort().reverse()[0];$('#last-updated').textContent=`Updated ${updated}`;$('#event-count').textContent=`${events.events.length} observed/emerging · ${prospective.milestones.length} prospective · ${named.cases.length} named regulatory cases`;fillSelect($('#stage'),[...new Set(state.records.flatMap(r=>r.stage||[]))].sort());fillSelect($('#institution'),[...new Set(state.records.flatMap(r=>actorsFor(r)).filter(Boolean))].sort());fillSelect($('#year'),[...new Set(state.records.map(normalizedYear).filter(Boolean))].sort().reverse());bind();renderEvidence();renderAnalysis();setView(location.hash.slice(1)||'roadmap')}catch(err){document.querySelector('main').innerHTML=`<p class="empty">Research companion data could not be loaded: ${esc(err.message)}</p>`}}
init();
