const state={records:[],search:'',stage:'all',institution:'all',year:'all',temporal:'all',major:true};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const label=s=>String(s??'').replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase());

function fillSelect(el,values){for(const value of values){const o=document.createElement('option');o.value=value;o.textContent=label(value);el.appendChild(o)}}
function normalizedYear(r){return (r.date||r.target_date||'').slice(0,4)}
function temporalClass(r){return r.record_type==='prospective'?'prospective':(r.temporal_status||'observed')}
function actorsFor(r){return r.record_type==='prospective'?(r.actors||[]):[r.institution]}
function filtered(){const q=state.search.toLowerCase().trim();return state.records.filter(r=>{
  if(state.major&&!r.major_milestone)return false;
  if(state.temporal!=='all'&&temporalClass(r)!==state.temporal)return false;
  if(state.stage!=='all'&&!(r.stage||[]).includes(state.stage))return false;
  if(state.institution!=='all'&&!actorsFor(r).includes(state.institution))return false;
  if(state.year!=='all'&&normalizedYear(r)!==state.year)return false;
  const blob=`${r.title} ${r.summary} ${r.why_it_matters||''} ${r.rationale||''} ${r.institution||''} ${(r.actors||[]).join(' ')} ${(r.stage||[]).join(' ')} ${(r.domain||[]).join(' ')}`.toLowerCase();
  if(q&&!blob.includes(q))return false;
  return true;
}).sort((a,b)=>(b.date||b.target_date||'').localeCompare(a.date||a.target_date||''))}
function countStage(records,stage){return records.filter(r=>(r.stage||[]).includes(stage)).length}
function renderObserved(e){return `<article class="event"><div class="event-date">${esc(e.display_date)}</div><div class="event-card"><div class="event-top"><div><div class="institution">${esc(e.institution)}</div><h2>${esc(e.title)}</h2></div><div class="badges"><span class="status time">${esc(label(temporalClass(e)))}</span><span class="status ${e.source_status==='primary_source_verified'?'verified':''}">${esc(label(e.source_status))}</span></div></div><p>${esc(e.summary)}</p>${e.why_it_matters?`<p class="why"><b>Why it matters.</b> ${esc(e.why_it_matters)}</p>`:''}<div class="tags">${(e.stage||[]).map(x=>`<span class="tag">${esc(label(x))}</span>`).join('')}${(e.domain||[]).map(x=>`<span class="tag">${esc(label(x))}</span>`).join('')}${e.major_milestone?'<span class="tag major-tag">Major milestone</span>':''}</div><p class="source">${e.source_url?`<a href="${esc(e.source_url)}" target="_blank" rel="noopener">Primary source ↗</a> · `:''}${esc(e.manuscript_ref||'')}</p></div></article>`}
function renderProspective(m){const criteria=(m.success_criteria||[]).map(x=>`<li>${esc(x)}</li>`).join('');return `<article class="event prospective"><div class="event-date">${esc(m.display_date)}</div><div class="event-card"><div class="event-top"><div><div class="institution">Prospective · ${esc(label(m.type))}</div><h2>${esc(m.title)}</h2></div><div class="badges"><span class="status prospective-status">Prospective</span><span class="status">${esc(label(m.status))}</span></div></div><p>${esc(m.summary)}</p><p class="why"><b>Why it matters.</b> ${esc(m.rationale)}</p>${criteria?`<div class="criteria"><b>What would count as success</b><ul>${criteria}</ul></div>`:''}<div class="tags">${(m.stage||[]).map(x=>`<span class="tag">${esc(label(x))}</span>`).join('')}${(m.domain||[]).map(x=>`<span class="tag">${esc(label(x))}</span>`).join('')}${m.major_milestone?'<span class="tag major-tag">Major milestone</span>':''}</div><p class="source">Actors: ${esc((m.actors||[]).join(' · '))}${m.paper_origin?` · Origin: ${esc(m.paper_origin)}`:''}</p></div></article>`}
function render(){const records=filtered();$('#visible-count').textContent=records.length;$('#commitment-count').textContent=countStage(records,'commitment');$('#qualification-count').textContent=countStage(records,'qualification');$('#adoption-count').textContent=countStage(records,'adoption');$('#prospective-count').textContent=records.filter(r=>r.record_type==='prospective').length;$('#empty').hidden=records.length>0;$('#timeline').innerHTML=records.map(r=>r.record_type==='prospective'?renderProspective(r):renderObserved(r)).join('')}
function bind(){$('#search').addEventListener('input',e=>{state.search=e.target.value;render()});$('#temporal').addEventListener('change',e=>{state.temporal=e.target.value;render()});$('#stage').addEventListener('change',e=>{state.stage=e.target.value;render()});$('#institution').addEventListener('change',e=>{state.institution=e.target.value;render()});$('#year').addEventListener('change',e=>{state.year=e.target.value;render()});$('#major').addEventListener('change',e=>{state.major=e.target.checked;render()});$('#reset').addEventListener('click',()=>{state.search='';state.stage='all';state.institution='all';state.year='all';state.temporal='all';state.major=true;$('#search').value='';$('#stage').value='all';$('#institution').value='all';$('#year').value='all';$('#temporal').value='all';$('#major').checked=true;render()})}
async function init(){try{const [er,pr]=await Promise.all([fetch('data/events.json',{cache:'no-store'}),fetch('data/prospective.json',{cache:'no-store'})]);if(!er.ok)throw new Error(`Events HTTP ${er.status}`);if(!pr.ok)throw new Error(`Prospective HTTP ${pr.status}`);const events=await er.json();const prospective=await pr.json();state.records=[...events.events.map(e=>({...e,record_type:'event'})),...prospective.milestones.map(m=>({...m,record_type:'prospective'}))];const updated=[events.updated,prospective.updated].sort().reverse()[0];$('#last-updated').textContent=`Updated ${updated}`;$('#event-count').textContent=`${events.events.length} observed/emerging · ${prospective.milestones.length} prospective`;fillSelect($('#stage'),[...new Set(state.records.flatMap(r=>r.stage||[]))].sort());fillSelect($('#institution'),[...new Set(state.records.flatMap(r=>actorsFor(r)).filter(Boolean))].sort());fillSelect($('#year'),[...new Set(state.records.map(normalizedYear).filter(Boolean))].sort().reverse());bind();render()}catch(err){$('#timeline').innerHTML=`<p class="empty">Roadmap data could not be loaded: ${esc(err.message)}</p>`}}
init();
